version: '3.8'

services:
  postgresql:
    image: postgres:13.7-alpine
    container_name: shareit-db
    ports:
      - "5433:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  server:
    container_name: shareit-server
    build: ./server
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - "TZ=Europe/Moscow"
      - DB_NAME=shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=postgresql
      - DB_PORT=5432

  gateway:
    container_name: shareit-gateway
    build: ./gateway
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - server
    environment:
      - SERVER_URL=http://server:9090